### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by Majkl578** [skrz/autowiring-bundle#8]
Symfony 4 is already GA, please add support for it. (Cascade dependency from Bunny.)

**Comment by mzstic** [comment]
I was already looking at it on Friday, imho even symfony 3.4 breaks this :(

**Comment by kockodev** [comment]
some news about this issue? Upgradability to Symfony4 is really apreciated :-)

**Comment by Majkl578** [comment]
This has been done in #9 and is in 1.3.0, just not been closed. :)
